name: Go CI Pipeline

on:
  push: # Run on push for every branch
    branches:
      - "*"

  pull_request: # Run on pull requests targeting the master branch
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Specify the Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Build the code
      run: go build ./...

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Specify the Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23 # Specify the Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Run benchmarks
      run: go test -bench=. ./... | tee benchmark-results.txt